### ISSUE TITLE
Entities unavailable after reinstall

### ISSUE THREAD

**Issue by mikesierra555** [rainepretorius/olarm-ha-integration#44]
I had a problem similar to issue #40  where my alarm_panel entities were unavailable after restart. The workaround was to delete and reinstall the integration, but now I have the problem that no entities are pulling through.

**Attempted the following:**

1. Regenerating api_key and reconfiguring the integration
2. Deleted integration, removed from HACS, reinstalled as per documentation

**Latest log:**

Logger: homeassistant.config_entries
Source: helpers/entity_component.py:179
First occurred: 1:22:42 PM (15 occurrences)
Last logged: 1:22:43 PM

Error setting up entry Olarm Sensors for alarm_control_panel
Error setting up entry Olarm Sensors for binary_sensor
Error setting up entry Olarm Sensors for button
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 115, in async_setup_entry
    return await component.async_setup_entry(entry)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 179, in async_setup_entry
    raise ValueError("Config entry has already been setup!")
ValueError: Config entry has already been setup!

**Comment by rainepretorius** [comment]
Hi @mikesierra555,
THis issue has been fixed in 2.0.9

**Comment by mikesierra555** [comment]
Hi @rainepretorius 

Thank you, but my issue still appears unresolved. Now getting a 404 error also, despite the html API call returning a normal response. Error below is repeat for button, switch and binary_sensor.

Error while setting up olarm_sensors platform for alarm_control_panel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/olarm_sensors/alarm_control_panel.py", line 37, in async_setup_entry
    await coordinator.async_get_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 157, in async_get_data
    return await self.update_data()
  File "/config/custom_components/olarm_sensors/coordinator.py", line 94, in update_data
    self.data = await self.api.get_sensor_states(devices_json)
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 123, in get_sensor_states
    time.ctime(int(olarm_state["zonesStamp"][zone]) / 1000),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

**Comment by rainepretorius** [comment]
Wil Look into it and push a fix asap.

**Comment by MrPrisoner** [comment]
Hi,

My entities also disappeared after update to 2.1.0

Logger: homeassistant.config_entries
Source: custom_components/olarm_sensors/olarm_api.py:523
Integration: Olarm Sensors ([documentation](https://github.com/rainepretorius/olarm-ha-integration/blob/main/README.md), [issues](https://github.com/rainepretorius/olarm-ha-integration/issues))
First occurred: 8:59:13 AM (1 occurrences)
Last logged: 8:59:13 AM

Error setting up entry Olarm Sensors for olarm_sensors
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/olarm_sensors/__init__.py", line 50, in async_setup_entry
    devices = await setup_api.get_olarm_devices()
  File "/config/custom_components/olarm_sensors/olarm_api.py", line 523, in get_olarm_devices
    olarm_resp = await response.json()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://apiv4.olarm.co/api/v4/devices')

I regenerated API key and reconfigured integration, I can get response from devices api call
https://apiv4.olarm.co/api/v4/devices/<redacted>?accessToken=<redacted>

**Comment by rainepretorius** [comment]
> Hi,
> 
> My entities also disappeared after update to 2.1.0
> 
> I get this error for all entity types (button, switch, binary_sensor, alarm_control_panel)
> 
> ```
> 2023-05-25 09:28:29.271 ERROR (MainThread) [homeassistant.components.button] Error while setting up olarm_sensors platform for button
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
> await asyncio.shield(task)
> File "/config/custom_components/olarm_sensors/button.py", line 28, in async_setup_entry
> await coordinator.async_get_data()
> File "/config/custom_components/olarm_sensors/coordinator.py", line 156, in async_get_data
> return await self.update_data()
> File "/config/custom_components/olarm_sensors/coordinator.py", line 111, in update_data
> change_json = await self.api.get_changed_by_json(i + 1)
> File "/config/custom_components/olarm_sensors/olarm_api.py", line 66, in get_changed_by_json
> changes = await response.json()
> File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1104, in json
> raise ContentTypeError(
> aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain; charset=utf-8', url=URL('https://apiv4.olarm.co/api/v4/devices/REDACTED/actions')
> ```
> 
> I regenerated API key and reconfigured integration.
> 
> Testing in the browser I get valid response from devices api call
> `https://apiv4.olarm.co/api/v4/devices/REDACTED?accessToken=REDACTED`
> 
> But the GET on actions (noted in HA error) returns Forbidden
> `https://apiv4.olarm.co/api/v4/devices/REDACTED/actions?accessToken=REDACTED`
> 
> The GET on events works fine though
> `https://apiv4.olarm.co/api/v4/devices/REDACTED/events?accessToken=REDACTED`
> 
> Maybe an issue with Olarm API?

I have also been getting this issue on my Zone sensors. It seems like there is some issue with the api. Because I get a text response of 500 Server error instead of the json data.

**Comment by louisklopper** [comment]
Home Assistant Core
2023-05-26 11:54:37.179 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration olarm_sensors which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-05-26 11:54:52.639 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Olarm Sensors for olarm_sensors
File "/config/custom_components/olarm_sensors/__init__.py", line 214, in update_listener
File "/config/custom_components/olarm_sensors/__init__.py", line 49, in async_setup_entry
File "/config/custom_components/olarm_sensors/__init__.py", line 234, in update_listener

**Comment by MrPrisoner** [comment]
Awesome, thanks Raine, worked like a charm!

**Comment by mikesierra555** [comment]
Thanks for the update. I'm still getting the forbidden or "too many requests" text responses no matter what I try. Keep the issue closed. I'll send olarm a support request.

**Comment by rainepretorius** [comment]
> Thanks for the update. I'm still getting the forbidden or "too many requests" text responses no matter what I try. Keep the issue closed. I'll send olarm a support request. 

I also mailed their CTO. We are currently in the process of trying to figure it out.

**Comment by muhammadqasimc** [comment]
@rainepretorius any update from olarm?
